program: src/train.py
project: sdg4ad
entity: canopies-diag
method: grid
metric:
  name: Best Model Balanced Accuracy
  goal: maximize
parameters:
  lr:
    value: 0.00001
  weight_decay:
    value: 0.0
  split:
    values: [1, 2, 3]
  batch_size:
    value: 32