program: train.py
project: sdg4ad
entity: canopies-diag
method: grid
metric:
  name: Validation Loss
  goal: minimize
parameters:
  lr:
    values: [0.01, 0.001, 0.0001, 0.00001, 0.000001, 0.0000001]
  split:
    values: [1, 2, 3, 4, 5]
  batch_size:
    value: 32