program: src/train.py
project: sdg4ad
entity: canopies-diag
method: grid
metric:
  name: Validation Balanced Accuracy
  goal: maximize
parameters:
  lr:
    values: [0.001, 0.0001, 0.00001, 0.000001]
  weight_decay:
    values: [0.001, 0.0001, 0.00001, 0.000001]
  split:
    values: [1, 2, 3]
  batch_size:
    value: 64
  early_stopping:
    value: True