seed: 42
file_path: 'data/Splits/PN/split_1_train.txt'
output_path: "output/split_1_train_v4"
target_size: "720p"  # Resolution of the generated images. Must be one of "720p", "1080p", "1440p", "4K"
plot: False  # If True, plots results for various stages of the pipeline

# SAM
sam_checkpoint: "weights/sam_vit_h_4b8939.pth"
model_type: "vit_h"
device: "cuda"
points_per_side: 16

# Canny
sigma: 5
partition: 50
lower_th_a: 80
upper_th_a: 160
lower_th_b: 80
upper_th_b: 240