seed: 42
splits_path: data/Splits/PN/
split: 1
epochs: 100
early_stopping: True
patience: 20
lr: 0.0001
batch_size: 1
num_workers: 4
mixed_precision: False
checkpoint_dir: output/checkpoints/
wandb_mode: online  # offline, online, disabled