seed: 42
train_splits_path: data/Splits/PN_addition_10/
val_splits_path: data/Splits/PN/
split: 1
epochs: 100
early_stopping: False
patience: 20
lr: 0.00001
batch_size: 16
num_workers: 4
mixed_precision: False
checkpoint_dir: output/checkpoints/
wandb_mode: online  # offline, online, disabled