seed: 42
splits_path: data/Splits/PN/
split: 1
epochs: 100
early_stopping: True
patience: 20
lr: 0.001
batch_size: 16
num_workers: 4
mixed_precision: True
checkpoint_dir: output/checkpoints/
wandb_mode: disabled  # offline, online, disabled
cae_inference_interval: 10