seed: 42
file_paths: ['data/Splits/PN/split_1_train.txt',
            'data/Splits/PN/split_2_train.txt',
            'data/Splits/PN/split_3_train.txt',
            'data/Splits/PN/split_4_train.txt',
            'data/Splits/PN/split_5_train.txt']
output_paths: ["output/synthetic_images/split_1",
              "output/synthetic_images/split_2",
              "output/synthetic_images/split_3",
              "output/synthetic_images/split_4",
              "output/synthetic_images/split_5"]
target_size: "1080p"  # Resolution of the generated images. Must be one of "720p", "1080p", "1440p", "4K"
plot: False  # If True, plots results for various stages of the pipeline

# SAM
sam_checkpoint: "weights/sam_vit_h_4b8939.pth"
model_type: "vit_h"
device: "cuda"
points_per_side: 16

# Canny
sigma: 5
partition: 50
lower_th_a: 80
upper_th_a: 160
lower_th_b: 80
upper_th_b: 240