seed: 42
train_splits_path: data/Splits/PN/
val_splits_path: data/Splits/PN/
split: 1
epochs: 100
lr: 0.0001
batch_size: 16
num_workers: 4
mixed_precision: False
checkpoint_dir: output/checkpoints/
wandb_mode: online  # offline, online, disabled