seed: 42
file_paths: ['data/Splits/PN/split_1_train.txt',
            'data/Splits/PN/split_2_train.txt',
            'data/Splits/PN/split_3_train.txt']
output_paths: ["output/synthetic_images_PN/split_1",
              "output/synthetic_images_PN/split_2",
              "output/synthetic_images_PN/split_3"]

# SAM
sam_checkpoint: "weights/sam_vit_h_4b8939.pth"
model_type: "vit_h"
device: "cuda"
points_per_side: 32

# Canny
sigma: 5
keep_ratio: 0.5
lower_th_a: 80
upper_th_a: 160
lower_th_b: 80
upper_th_b: 240