seed: 42
file_path: "data/Splits/PN/split_2_train.txt"
output_path: "data/synthetic_images_PN/split_2"

# SAM
sam_checkpoint: "weights/sam_vit_h_4b8939.pth"
model_type: "vit_h"
device: "cuda"
points_per_side: 32

# Canny
keep_ratio: 0.5
kernel_size: 3
lower_th_wide: 0
upper_th_wide: 100
lower_th_narrow: 25
upper_th_narrow: 200