seed: 42
file_path: "data/Splits/PN/split_3_train.txt"
output_path: "output/synthetic_images_PN/split_3"

# SAM
sam_checkpoint: "weights/sam_vit_h_4b8939.pth"
model_type: "vit_h"
device: "cuda"
points_per_side: 32

# Canny
keep_ratio: 0.5
kernel_size: 3
lower_th_wide: 25
upper_th_wide: 50
lower_th_narrow: 75
upper_th_narrow: 200